import type { Metadata } from "next"

export const metadata: Metadata = {
    title: "About page",
    description: "Generated by Pak_011",
    keywords: ['About Page', 'PAKO', 'Informacion', '...']
}

export default function AboutPage() {
    return (
        <>
            <span className="text-7xl">About Page</span>
        </>
    )
}